# Generated by Django 5.0 on 2024-02-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='total',
            new_name='precio_total',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='salario',
        ),
    ]
